[package]
name = "click_mute"
version = "0.1.0"
authors = ["Erkki Seppälä <erkki.seppala@vincit.fi>"]
edition = "2018"

[dependencies]
jack = "0.7"
evdev = "0.10.2"
libc = "0.2.81"
crossbeam-channel = "0.3.9"

# [lib]
# name = "mute_keyboard_plugin"
# crate-type = ["dylib"]
